# Generated by Django 3.2.13 on 2022-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
    ]
