# Generated by Django 3.2.13 on 2022-05-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticker',
            field=models.TextField(default='tbd', max_length=6),
            preserve_default=False,
        ),
    ]
