# Generated by Django 3.2.13 on 2022-05-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ticker',
            new_name='StockTicker',
        ),
    ]
