# Generated by Django 3.2.13 on 2022-05-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_ticker_post_stockticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='StockTicker',
        ),
    ]
