# Generated by Django 3.2.13 on 2022-05-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
